name: Java CI with Maven

on:
  push:
    branches:
      - main
      - search-sort-for-unit-tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven tests
        working-directory: campus-shuttle-optimizer/campus-shuttle-optimizer
        run: mvn test
